/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import classes.Employee; //to access the necessary properties of the Employee class
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Dialog;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DREAM PC
 */
public class FrmDeleteEmployee extends javax.swing.JDialog {

    /**
     * Creates new form FrmDeleteEmployee
     */
    public FrmDeleteEmployee(Employee _employee) {
        initComponents();
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            txtEmployeeNo.setText(_employee.GetEmployeeNo());
            txtLastName.setText(_employee.GetLastName());
            txtFirstName.setText(_employee.GetFirstName());
            txtSSSNo.setText(_employee.GetSSSNo());
            txtPhealthNo.setText(_employee.GetPhealthNo());
            txtTinNo.setText(_employee.GetTinNo());
            txtPagibigNo.setText(_employee.GetPagibigNo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        lblEmployeeNo = new javax.swing.JLabel();
        txtEmployeeNo = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblSSSNo = new javax.swing.JLabel();
        txtSSSNo = new javax.swing.JTextField();
        lblPhealthNo = new javax.swing.JLabel();
        txtPhealthNo = new javax.swing.JTextField();
        lblTinNo = new javax.swing.JLabel();
        txtTinNo = new javax.swing.JTextField();
        lblPagibigNo = new javax.swing.JLabel();
        txtPagibigNo = new javax.swing.JTextField();
        btnDeleteEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseFrame(evt);
            }
        });

        lblEmployeeNo.setText("Employee No.:");

        txtEmployeeNo.setEditable(false);

        lblLastName.setText("Last Name:");

        txtLastName.setEditable(false);

        lblFirstName.setText("First Name:");

        txtFirstName.setEditable(false);

        lblSSSNo.setText("SSS No.:");

        txtSSSNo.setEditable(false);

        lblPhealthNo.setText("PhilHealth No.:");

        txtPhealthNo.setEditable(false);

        lblTinNo.setText("TIN No.:");

        txtTinNo.setEditable(false);

        lblPagibigNo.setText("Pagibig No.:");

        txtPagibigNo.setEditable(false);

        btnDeleteEmployee.setText("Delete Employee Record");
        btnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteEmployee(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeNo)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName)
                            .addComponent(lblSSSNo)
                            .addComponent(lblPhealthNo)
                            .addComponent(lblTinNo)
                            .addComponent(lblPagibigNo))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployeeNo)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtFirstName)
                            .addComponent(txtSSSNo)
                            .addComponent(txtPhealthNo)
                            .addComponent(txtTinNo)
                            .addComponent(txtPagibigNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeNo)
                    .addComponent(txtEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSSNo)
                    .addComponent(txtSSSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhealthNo)
                    .addComponent(txtPhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTinNo)
                    .addComponent(txtTinNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagibigNo)
                    .addComponent(txtPagibigNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmployee)
                    .addComponent(btnClose))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseFrame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseFrame
        this.dispose();
    }//GEN-LAST:event_CloseFrame

    // event handler method for Delete Employee button
    private void DeleteEmployee(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEmployee
        Employee _employee = new Employee();
        _employee.SetEmployeeNo(txtEmployeeNo.getText());
        _employee.SetLastName(txtLastName.getText());
        _employee.SetFirstName(txtFirstName.getText());
        _employee.SetSSSNo(txtSSSNo.getText());
        _employee.SetPhealthNo(txtPhealthNo.getText());
        _employee.SetTinNo(txtTinNo.getText());
        _employee.SetPagibigNo(txtPagibigNo.getText());
        String csvFilename = "Employees.csv";
        try {
            _employee.DeleteEmployee(csvFilename);
            txtEmployeeNo.setText("");
            txtLastName.setText("");
            txtFirstName.setText("");
            txtSSSNo.setText("");
            txtPhealthNo.setText("");
            txtTinNo.setText("");
            txtPagibigNo.setText("");
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmDeleteEmployee.class.getName()).log(Level.INFO, "An unexpected error occured.", ex);
        }
    }//GEN-LAST:event_DeleteEmployee

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JLabel lblEmployeeNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPagibigNo;
    private javax.swing.JLabel lblPhealthNo;
    private javax.swing.JLabel lblSSSNo;
    private javax.swing.JLabel lblTinNo;
    private javax.swing.JTextField txtEmployeeNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPagibigNo;
    private javax.swing.JTextField txtPhealthNo;
    private javax.swing.JTextField txtSSSNo;
    private javax.swing.JTextField txtTinNo;
    // End of variables declaration//GEN-END:variables
}
